### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by ZachIsAGardner** [ZachIsAGardner/Shmetsy#9]

**Comment by mikeboan** [comment]
styling could use some love

**Comment by mikeboan** [comment]
clear errors on form change

**Comment by mikeboan** [comment]
Can you remove the weird gray border that goes around the entire page?

**Comment by mikeboan** [comment]
header styling could use some work

**Comment by mikeboan** [comment]
Same with session form

**Comment by mikeboan** [comment]
Styling in general needs some work. Looks like you have a lot of features up but none are 100% styled. Take a few hours and polish everything up before moving on.
